const PostCardList = [
    {
        id: 1,
        isOpenArray: true,
        date: "1/21/2024",
        cardClass:'multi_days',
        cardHeading: 'International Music Concert ',
        dayTagText: 'Day 1/3',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sarah Sampson',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/cash-register-icon.png'),
        percentageText: '',
        tooltipText2: 'Post Paid',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
        id: 2,
        isOpenArray: false,
        date: "1/20/2024",
        cardClass:'single_days',
        cardHeading: ' Music Concert ',
        dayTagText: '',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sarah Sampson',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/percentage-icon.png'),
        percentageText: '30%',
        tooltipText2: 'Total Amount',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
        id: 3,
        isOpenArray: false,
        date: "1/13/2024",
        cardClass:'multi_days',
        cardHeading: 'International Concert ',
        dayTagText: 'Day 1/3',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sarah Sampson',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/cash-register-icon.png'),
        percentageText: '',
        tooltipText2: 'Post Paid',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
        id: 4,
        isOpenArray: true,
        date: "1/14/2024",
        cardClass:'single_days',
        cardHeading: 'International Music ',
        dayTagText: '',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sarah Sampson',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/percentage-icon.png'),
        percentageText: '40%',
        tooltipText2: 'Total Amount',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
        id: 5,
        isOpenArray: false,
        date: "1/15/2024",
        cardClass:'single_days',
        cardHeading: 'International Music Concert ',
        dayTagText: '',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sarah Sampson',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/percentage-icon.png'),
        percentageText: '70%',
        tooltipText2: 'Total Amount',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
        id: 6,
        isOpenArray: false,
        date: "1/16/2024",
        cardClass:'multi_days',
        cardHeading: 'International Music Concert ',
        dayTagText: 'Day 1/3',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sarah Sampson',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/cash-register-icon.png'),
        percentageText: '',
        tooltipText2: 'Post Paid',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
        id: 7,
        isOpenArray: true,
        date: "1/17/2024",
        cardClass:'single_days',
        cardHeading: 'International Music Concert ',
        dayTagText: '',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sarah Sampson',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/percentage-icon.png'),
        percentageText: '10%',
        tooltipText2: 'Total Amount',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
        id: 8,
        isOpenArray: false,
        date: "1/18/2024",
        cardClass:'single_days',
        cardHeading: 'International Music Concert ',
        dayTagText: '',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sarah',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/percentage-icon.png'),
        percentageText: '50%',
        tooltipText2: 'Total Amount',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
        id: 9,
        isOpenArray: true,
        date: "1/19/2024",
        cardClass:'single_days',
        cardHeading: 'International Music Concert ',
        dayTagText: '',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sampson',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/percentage-icon.png'),
        percentageText: '60%',
        tooltipText2: 'Total Amount',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
        id: 10,
        isOpenArray: false,
        date: "1/10/2024",
        cardClass:'single_days',
        cardHeading: 'International Music Concert ',
        dayTagText: '',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sarah Sampson',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/percentage-icon.png'),
        percentageText: '30%',
        tooltipText2: 'Total Amount',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
        id: 11,
        isOpenArray: true,
        date: "1/11/2024",
        cardClass:'single_days',
        cardHeading: 'International Music Concert ',
        dayTagText: '',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sarah Sampson',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/percentage-icon.png'),
        percentageText: '50%',
        tooltipText2: 'Total Amount',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
        id: 12,
        isOpenArray: false,
        date: "1/12/2024",
        cardClass:'single_days',
        cardHeading: 'International Music Concert ',
        dayTagText: '',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sarah Sampson',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/percentage-icon.png'),
        percentageText: '70%',
        tooltipText2: 'Total Amount',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
        id: 13,
        isOpenArray: false,
        date: "1/13/2024",
        cardClass:'single_days',
        cardHeading: 'International Music Concert ',
        dayTagText: '',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sarah Sampson',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/percentage-icon.png'),
        percentageText: '80%',
        tooltipText2: 'Total Amount',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
        id: 14,
        isOpenArray: true,
        date: "1/14/2024",
        cardClass:'single_days',
        cardHeading: 'International Music Concert ',
        dayTagText: '',
        TimeText: '4:00PM - 9:00PM',
        LocationText: '36 Guild Street London , UK',
        profileImg: require('../../assets/images/profile-img2.png'),
        userLinkk: '',
        userName: 'Sarah Sampson',
        userPost: 'Event Manager',
        infoIcon1: require('../../assets/images/martini-icon.png'),
        tooltipText1: 'Martini',
        infoIcon2: require('../../assets/images/percentage-icon.png'),
        percentageText: '30%',
        tooltipText2: 'Total Amount',
        infoIcon3: require('../../assets/images/information-icon.png'),
        tooltipText3: 'Completed',
        taskRedNum: '5',
        taskYellowNum: '3',
        taskGreenNum: '8',
        totalTaskNum: '16',
        equipmentRedNum: '5',
        equipmentYellowNum: '3',
        equipmentGreenNum: '8',
        totalEquipmentNum: '16',
        inventoryRedNum: '5',
        inventoryYellowNum: '3',
        inventoryGreenNum: '8',
        totalInventoryNum: '16',
        staffingRedNum: '5',
        staffingYellowNum: '3',
        staffingGreenNum: '8',
        totalStaffingNum: '16',
        salesMoney: '£1,000,000',
        profitMoney: '£1,000,000',
    },
    {
      id: 15,
      isOpenArray: true,
      date: "1/15/2024",
      cardClass: "multi_days",
      cardHeading: "International Music Concert ",
      dayTagText: 'Day 1/3',
      TimeText: "4:00PM - 9:00PM",
      LocationText: "36 Guild Street London , UK",
      profileImg: require("../../assets/images/profile-img2.png"),
      userLinkk: "",
      userName: "Sarah Sampson",
      userPost: "Event Manager",
      infoIcon1: require("../../assets/images/martini-icon.png"),
      tooltipText1: "Martini",
      infoIcon2: require("../../assets/images/percentage-icon.png"),
      percentageText: "30%",
      tooltipText2: "Total Amount",
      infoIcon3: require("../../assets/images/information-icon.png"),
      tooltipText3: "Completed",
      taskRedNum: '5',
      taskYellowNum: '3',
      taskGreenNum: '8',
      totalTaskNum: '16',
      equipmentRedNum: '5',
      equipmentYellowNum: '2',
      equipmentGreenNum: '6',
      totalEquipmentNum: '13',
      inventoryRedNum: '4',
      inventoryYellowNum: '3',
      inventoryGreenNum: '5',
      totalInventoryNum: '12',
      staffingRedNum: '5',
      staffingYellowNum: '3',
      staffingGreenNum: '8',
      totalStaffingNum: '16',
      salesMoney: '£1,000,000',
      profitMoney: '£1,000,000',
    },
    {
      id: 16,
      isOpenArray: false,
      date: "1/15/2024",
      cardClass: "single_days",
      cardHeading: "International Music Concert ",
      dayTagText: "",
      TimeText: "4:00PM - 9:00PM",
      LocationText: "36 Guild Street London , UK",
      profileImg: require("../../assets/images/profile-img2.png"),
      userLinkk: "",
      userName: "Sarah Sampson",
      userPost: "Event Manager",
      infoIcon1: require("../../assets/images/martini-icon.png"),
      tooltipText1: "Martini",
      infoIcon2: require("../../assets/images/percentage-icon.png"),
      percentageText: "30%",
      tooltipText2: "Total Amount",
      infoIcon3: require("../../assets/images/information-icon.png"),
      tooltipText3: "Completed",
      taskRedNum: '6',
      taskYellowNum: '4',
      taskGreenNum: '6',
      totalTaskNum: '16',
      equipmentRedNum: '4',
      equipmentYellowNum: '0',
      equipmentGreenNum: '8',
      totalEquipmentNum: '12',
      inventoryRedNum: '5',
      inventoryYellowNum: '3',
      inventoryGreenNum: '8',
      totalInventoryNum: '16',
      staffingRedNum: '5',
      staffingYellowNum: '3',
      staffingGreenNum: '8',
      totalStaffingNum: '16',
      salesMoney: '£1,000,000',
      profitMoney: '£1,000,000',
    },
    {
      id: 17,
      isOpenArray: true,
      date: "1/17/2024",
      cardClass: "single_days",
      cardHeading: "International Music Concert ",
      dayTagText: "",
      TimeText: "4:00PM - 9:00PM",
      LocationText: "36 Guild Street London , UK",
      profileImg: require("../../assets/images/profile-img2.png"),
      userLinkk: "",
      userName: "Sarah Sampson",
      userPost: "Event Manager",
      infoIcon1: require("../../assets/images/martini-icon.png"),
      tooltipText1: "Martini",
      infoIcon2: require("../../assets/images/percentage-icon.png"),
      percentageText: "30%",
      tooltipText2: "Total Amount",
      infoIcon3: require("../../assets/images/information-icon.png"),
      tooltipText3: "Completed",
      taskRedNum: '5',
      taskYellowNum: '3',
      taskGreenNum: '8',
      totalTaskNum: '16',
      equipmentRedNum: '5',
      equipmentYellowNum: '3',
      equipmentGreenNum: '8',
      totalEquipmentNum: '16',
      inventoryRedNum: '5',
      inventoryYellowNum: '3',
      inventoryGreenNum: '8',
      totalInventoryNum: '16',
      staffingRedNum: '5',
      staffingYellowNum: '3',
      staffingGreenNum: '8',
      totalStaffingNum: '16',
      salesMoney: '£1,000,000',
      profitMoney: '£1,000,000',
    },
    {
      id: 18,
      isOpenArray: true,
      date: "1/1/2024",
      cardClass: "single_days",
      cardHeading: "International Music Concert ",
      dayTagText: "",
      TimeText: "4:00PM - 9:00PM",
      LocationText: "36 Guild Street London , UK",
      profileImg: require("../../assets/images/profile-img2.png"),
      userLinkk: "",
      userName: "Sarah Sampson",
      userPost: "Event Manager",
      infoIcon1: require("../../assets/images/martini-icon.png"),
      tooltipText1: "Martini",
      infoIcon2: require("../../assets/images/percentage-icon.png"),
      percentageText: "30%",
      tooltipText2: "Total Amount",
      infoIcon3: require("../../assets/images/information-icon.png"),
      tooltipText3: "Completed",
      taskRedNum: '5',
      taskYellowNum: '3',
      taskGreenNum: '8',
      totalTaskNum: '16',
      equipmentRedNum: '5',
      equipmentYellowNum: '3',
      equipmentGreenNum: '8',
      totalEquipmentNum: '16',
      inventoryRedNum: '5',
      inventoryYellowNum: '3',
      inventoryGreenNum: '8',
      totalInventoryNum: '16',
      staffingRedNum: '5',
      staffingYellowNum: '3',
      staffingGreenNum: '8',
      totalStaffingNum: '16',
      salesMoney: '£1,000,000',
      profitMoney: '£1,000,000',
    },
    {
      id: 19,
      isOpenArray: true,
      date: "1/28/2024",
      cardClass: "single_days",
      cardHeading: "International Music Concert ",
      dayTagText: "",
      TimeText: "4:00PM - 9:00PM",
      LocationText: "36 Guild Street London , UK",
      profileImg: require("../../assets/images/profile-img2.png"),
      userLinkk: "",
      userName: "Sarah Sampson",
      userPost: "Event Manager",
      infoIcon1: require("../../assets/images/martini-icon.png"),
      tooltipText1: "Martini",
      infoIcon2: require("../../assets/images/percentage-icon.png"),
      percentageText: "30%",
      tooltipText2: "Total Amount",
      infoIcon3: require("../../assets/images/information-icon.png"),
      tooltipText3: "Completed",
      taskRedNum: '5',
      taskYellowNum: '3',
      taskGreenNum: '8',
      totalTaskNum: '16',
      equipmentRedNum: '5',
      equipmentYellowNum: '3',
      equipmentGreenNum: '8',
      totalEquipmentNum: '16',
      inventoryRedNum: '5',
      inventoryYellowNum: '3',
      inventoryGreenNum: '8',
      totalInventoryNum: '16',
      staffingRedNum: '5',
      staffingYellowNum: '3',
      staffingGreenNum: '8',
      totalStaffingNum: '16',
      salesMoney: '£1,000,000',
      profitMoney: '£1,000,000',
    },
]

export default PostCardList;
