export const LOGIN = "/"
export const HOME =  "/home"
export const FORGETPASSWORD = "/forgetpassword"
export const CUSTOMERLIST = "/home/:module_name"
export const CALENDAR = "/home/calendar"
export const DETAILEDVIEW = "/home/:module_name/detail/:id"
export const DETAILEDVIEW1 = "/home/:module_name/detail-op/:id"
export const CREATEMODULEPAGE = "/home/:module_name/add-edit"
export const SUPPLIERRECEIPTPAGE= "home/:module_name/add-edit&supplierorder=/:id"
export const CREATEMODULEPAGE1 = "/home/:module_name/add-edit-op"
export const RELATEDLIST = "home/:prev_module_name/relatedlist/:pvid"
export const RELATEDLISTDETAILEDVIEWFOROP="/home/:e_module_name/:epid/detail-op/:module_name/:id"
export const RELATEDLISTDETAILEDVIEW="/home/:e_module_name/:epid/detail/:module_name/:id"
export const NOTESMODULE="home/:prev_module_name/relatedlist/nn/:pvid"
export const REPORTDETAILSPAGE="home/:module_name/reportdetails/:reportid"
export const CREATEREPORTMODULEPAGE = "/home/:module_name/add-edit-report"
export const REPORTCREATEPAGE="home/:module_name/add-edit-report/:said"
export const EVENTMANAGEMENTPAGE="home/event"

export const RELATEDETAILEDVIEW = "/home/:r_module_name/relatedlist/:r_id/:module_name/detail/:id"
